services:
   foodway-backend:
     image: fernandeeess/foodway-api:3.0
     ports:
       - "5225:8080"
     environment:
       DB_PASS: ${DB_PASS}
       DB_URL: ${DB_URL}
       DB_USER: ${DB_USER}
       JWT_SECRET: ${JWT_SECRET}
       GMAPS_API_KEY: ${GMAPS_API_KEY}
       BUCKET_NAME: ${BUCKET_NAME}
       ACCESS_KEY: ${ACCESS_KEY}
       SECRET: ${SECRET}
       REGION: ${REGION}
       SESSION_TOKEN: ${SESSION_TOKEN}
     networks:
       - foodway

   prometheus:
     image: prom/prometheus
     ports:
       - "9090:9090"
     volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
     networks:
       - foodway
     depends_on:
       - foodway-backend

   grafana:
     image: grafana/grafana
     ports:
       - "3000:3000"
     networks:
       - foodway
     depends_on:
       - prometheus
   postgres:
     image: postgres:12
     environment:
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASS}
       POSTGRES_DB: ${DB_NAME}
     volumes:
       - ./dump.sql:/docker-entrypoint-initdb.d/your_dump_file.sql
     ports:
       - "5432:5432"
     networks:
       - foodway


networks:
  foodway:
    driver: bridge
