name: Build, Push to Docker Hub, and Deploy Nginx Website (with Localhost Check)

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List files in workspace for debugging
        run: ls -la

      - name: Login to Docker Hub (using encrypted credentials)
        uses: docker/login-action@v2
        with:
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password:  ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to Docker Hub
        run: |
          docker build -t fernandeeess/foodway-api:latest .
          docker push fernandeeess/foodway-api:latest

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: "10.0.0.139"
          username: "ubuntu"
          key: ${{ secrets.FOODWAY }}
          script: |
            sudo docker pull fernandeeess/foodway-api
            sudo docker run -p 80:80 -p 8080:8080 -p 443:443 -d fernandeeess/foodway-api
