name: CI/CD Pipeline - Foodway

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./API

      - name: Run Unit Tests
        run: mvn test
        working-directory: ./API

      - name: Run Integration Tests
        run: mvn verify
        working-directory: ./API

      - name: Check Code Coverage
        run: mvn jacoco:report
        working-directory: ./API

      - name: List files for debugging
        run: ls -la API/target

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/foodway-api:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/foodway-api:latest

      - name: Install netcat
        run: sudo apt-get install -y netcat

      - name: Health Check for backend-01 Server via Bastion Host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          script: |
            if ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/ssh_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST_PRIVATE_ONE }} "nc -z -w5 localhost 22"; then
              echo "backend-01 is up"
            else
              echo "backend-01 is down"
              exit 1
            fi

      - name: Health Check for backend-02 Server via Bastion Host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          script: |
            if ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/ssh_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST_PRIVATE_TWO }} "nc -z -w5 localhost 22"; then
              echo "backend-02 is up"
            else
              echo "backend-02 is down"
              exit 1
            fi

      - name: Deploy to backend-01 Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          script: |
            ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/ssh_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST_PRIVATE_ONE }} << EOF
              sudo docker-compose -f /home/ubuntu/AWS/docker-compose.yml down
              sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/foodway-api
              sudo docker-compose -f /home/ubuntu/AWS/docker-compose.yml up -d
            EOF
      

      - name: Deploy to backend-02 Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_SSH_KEY }}
          script: |
            ssh -o StrictHostKeyChecking=no \
                -i /home/ubuntu/.ssh/ssh_key.pem \
                -t ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST_PRIVATE_TWO }} \
                "sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/foodway-api && sudo docker run -p 80:80 -p 5225:8080 -p 443:443 -d ${{ secrets.DOCKERHUB_USERNAME }}/foodway-api"